name: Run pre-commit checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python v3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
